// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDHxfKrnO1ePmyAOKMEJ4543pSCyAXArU',
    appId: '1:501364538277:web:3fb106732f1bb31c88c64c',
    messagingSenderId: '501364538277',
    projectId: 'lactomate-bb4a6',
    authDomain: 'lactomate-bb4a6.firebaseapp.com',
    storageBucket: 'lactomate-bb4a6.appspot.com',
    measurementId: 'G-VGCT44F7LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzIE-spr8KD7k181ECcFINTJXBOO699Tw',
    appId: '1:501364538277:android:fa9cbf1bf9198f6f88c64c',
    messagingSenderId: '501364538277',
    projectId: 'lactomate-bb4a6',
    storageBucket: 'lactomate-bb4a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj_vR9KhRnxJoQsVXwI9ECdUOgSJlvFwU',
    appId: '1:501364538277:ios:ec1a66f9155cc71288c64c',
    messagingSenderId: '501364538277',
    projectId: 'lactomate-bb4a6',
    storageBucket: 'lactomate-bb4a6.appspot.com',
    iosBundleId: 'com.example.lactomate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj_vR9KhRnxJoQsVXwI9ECdUOgSJlvFwU',
    appId: '1:501364538277:ios:ec1a66f9155cc71288c64c',
    messagingSenderId: '501364538277',
    projectId: 'lactomate-bb4a6',
    storageBucket: 'lactomate-bb4a6.appspot.com',
    iosBundleId: 'com.example.lactomate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDHxfKrnO1ePmyAOKMEJ4543pSCyAXArU',
    appId: '1:501364538277:web:92c3117e3513685a88c64c',
    messagingSenderId: '501364538277',
    projectId: 'lactomate-bb4a6',
    authDomain: 'lactomate-bb4a6.firebaseapp.com',
    storageBucket: 'lactomate-bb4a6.appspot.com',
    measurementId: 'G-W140NLT88G',
  );
}
